services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: lera_cooking_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - lera_cooking

  nginx:
    image: nginx:stable
    container_name: lera_cooking_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lera_cooking

  db:
    image: postgres:15
    container_name: lera_cooking_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lera_cooking_db
      POSTGRES_USER: lera_cooking_user
      POSTGRES_PASSWORD: poppoppop890
    volumes:
      - pgdata:/var/lib/postgresql/data\
    networks:
      - lera_cooking

volumes:
  pgdata:
networks:
  lera_cooking:
    driver: "bridge"